#公共配置
server:
    port: 8088
    tomcat:
      uri-encoding: UTF-8

spring:
    #激活哪一个环境的配置文件
    profiles:
      active: dev
    #视图配置
    mvc:
      static-path-pattern: /static/**
    aop:
      proxy-target-class: true
    datasource:
        jdbc-url: jdbc:mysql://localhost:3306/comadmin?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        maximum-pool-size: 30


    liquibase:
       change-log: classpath:liquibase/master.xml
       enabled: true
       drop-first: false

    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      password:
      timeout: 5000
      lettuce:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8
          max-wait: -1

  #七牛云配置
    qiniu:
      accessKey: VfZ3d39D8MbnU84IbsqRLRfQhSdvUaT0reqbjJ01
      secretKey: 1Mj8qJtKpCVwUAEuB7_4fsmbsOKTzm0xjYnub0Hd
      bucket: comadmin_pic
      path: pv0shc5j5.bkt.clouddn.com
      imageMaxSize: 52428800
      imageMaxNameLength: 200

  #qq邮箱配置
    mail:
      username: 2962559235@qq.com
      password: xnwdhcrjjthyddfe
      host: smtp.qq.com
      port: 25
      default-encoding: UTF-8

    #rabbitmq配置
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest



#mybatisPlu
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  typeAliasesPackage: com.xiaoshu.admin.entity
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: UUID
       #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      db-type: mysql
    #刷新mapper
    refresh-mapper: true
  #原生配置
  configuration:
    #开启驼峰功能
    map-underscore-to-camel-case: true
    cache-enabled: false

#日志
logging:
  config: classpath:logback.xml
  path: D:\logs\comadmin

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      appname: comadmin-task
    accessToken:


---
#开发环境配置
spring:
  profiles: dev
  #自定义配置属性
  #视图配置
  mvc:
    static-path-pattern: /static/**
  aop:
    proxy-target-class: true
  datasource:
      url: jdbc:mysql://localhost:3306/comadmin?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      maximum-pool-size: 30
server:
  #端口
  port: 8088



---
#测试环境配置
spring:
  profiles: test
  #自定义配置属性
  #视图配置
  mvc:
    static-path-pattern: /static/**
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://localhost:3306/comadmin?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    maximum-pool-size: 30
server:
  #端口
  port: 8085


---
#生产环境配置
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://localhost:3306/comadmin?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    maximum-pool-size: 30
server:
  port: 8080


